include:
  - project: $CATALOG_PATH
    file: vault-ci.yml
    ref: main
  - project: $CATALOG_PATH
    file: kaniko-ci.yml
    ref: main

default:
  image: alpine:latest

cache:
  paths:
    - node_modules

variables:
  REGISTRY_URL: "${REGISTRY_HOST}/${PROJECT_PATH}"

stages:
  - read-secret
  - docker-build

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

docker-build:
  variables:
    TAG: "${CI_COMMIT_REF_SLUG}"
    WORKING_DIR: ./
    DOCKERFILE: ./Dockerfile.bitnami
    IMAGE_NAMES: docs-services-socles:1.0 docs-services-socles:latest
  stage: docker-build
  extends:
    - .kaniko:build-push
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      variables:                              
        IMAGE_NAMES: docs-services-socles:dev  
    - if: $CI_COMMIT_BRANCH == "main"
      variables:                              
        IMAGE_NAMES: docs-services-socles:1.0 docs-services-socles:latest


