# The Docker image that will be used to build your app

# gitlabrunner partagé
default:
  tags:
    - shared
    - region1

variables:
  registry_url: nexus.forge-dc.cloudmi.minint.fr
  proxy_host: pio.service.consul
  proxy_port: 3128
  http_proxy: http://${proxy_host}:${proxy_port}
  https_proxy: http://${proxy_host}:${proxy_port}
  no_proxy: localhost,.pi2.minint.fr
  GIT_SSL_NO_VERIFY: "true"
image: node:18
stages:
  - pages
# Functions that should be executed before the build script is run
pages:
  stage: pages
  script:
    - npm install
    - npm run build
    - npm run postbuild
    - cp -pR _site/* public/
    - cp _site/fr/index.html public/
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
